CREATE DATABASE MARKET

USE MARKET

CREATE TABLE Products
(
   ID INT PRIMARY KEY,
   Name NVARCHAR(200) NOT NULL,
   Price FLOAT
)

INSERT INTO Products
VALUES
(1,'SAMPUN',7.50)
INSERT INTO Products
VALUES
(2,'SABUN',1.50),
(3,'ET',10.50),
(4,'UN',1.30),
(5,'YUMURTA',1),
(6,'CAY',7.50),
(7,'SIRE',3.40),
(8,'EDVIYYAT',0.60),
(9,'PALTARYUYAN tOZ',15.35),
(10,'KOLBASA',7.50)

SELECT ID,Name,Price FROM Products

SELECT * FROM Products WHERE Price>10

CREATE TABLE Brands
(
   ID INT IDENTITY PRIMARY KEY,
   Name NVARCHAR(100),
   BrandID INT CONSTRAINT FK_pRODUCTS_BRANDS FOREIGN KEY REFERENCES Products(ID)
)

INSERT INTO Brands
VALUES
('HEAD AND SOLUDERS',1),
('RET',2),
('BOL ET',3),
('KAEN',4),
('AZERYUMURTA',5),
('AZERCAY',6),
('NATURA',7),
('HACIKANRT',8),
('ARIEL',9),
('HALAL NEMET',10)



SELECT* FROM Brands

SELECT * FROM Brands WHERE LEN(Name)>5

SELECT AVG(Price) FROM Products

SELECT * FROM Products WHERE Price<( SELECT AVG(price) FROM Products)
