CREATE DATABASE KINOZALS

USE KINOZALS

CREATE TABLE MOVIES
(
ID INT IDENTITY PRIMARY KEY,
NAME NVARCHAR(200)
)

CREATE TABLE LAUNGUAGE
(
Id INT IDENTITY PRIMARY KEY,
Name NVARCHAR(50)
)
CREATE TABLE BRANCHES
(
Id INT IDENTITY PRIMARY KEY ,
Name NVARCHAR(50)
)

CREATE TABLE HALLS
(
Id INT IDENTITY PRIMARY KEY,
Name NVARCHAR(50),
BranchId INT FOREIGN KEY REFERENCES BRANCHES(Id)
)
CREATE TABLE MOVIELAUNGUAGE
(
Id INT IDENTITY PRIMARY KEY,
MovieId INT FOREIGN KEY  REFERENCES MOVIES(Id),
LanguageId INT FOREIGN KEY REFERENCES LAUNGUAGE(Id)
)
CREATE TABLE SEANSES
(
Id INT IDENTITY PRIMARY KEY,
Price MONEY,
MovieLanguageId INT FOREIGN KEY REFERENCES MOVIELAUNGUAGE(Id),
HallId INT FOREIGN KEY REFERENCES HALLS(Id),
Time DATETIME2 ,
SubtitleLanguageId INT FOREIGN KEY REFERENCES LAUNGUAGE(Id),
)

INSERT INTO MOVIES 
VALUES
('MOVIES 1'),
('MOVIES 2'),
('MOVIES 3')

INSERT INTO MOVIES
VALUES
('MOVIE 4')

INSERT INTO LAUNGUAGE
VALUES
('AZ'),
('RU'),
('EN')
INSERT INTO BRANCHES
VALUES
('ZAL 1'),
('ZAL 2'),
('ZAL 3')

INSERT INTO HALLS
VALUES
('KICIK OTAQ',1),
('ORTA OTAQ',2),
('BOYUK OTAQ',3)

INSERT INTO MOVIELAUNGUAGE
VALUES
(1,3),
(2,1),
(3,2)

INSERT INTO SEANSES
VALUES
(5,1,1,'2020/11/5',3),
(6,2,1,'2020/11/6',1),
(5,2,2,'2020/11/7',1),
(7,1,2,'2020/11/8',3),
(7,3,3,'2020/11/9',2),
(10,3,3,'2020/11/10',2)

INSERT INTO SEANSES
VALUES
(9,1,2,'2020/11/11',3)

SELECT * FROM SEANSES

--task1

SELECT * FROM Seanses
WHERE Time LIKE '2020/11/10'

--task2

SELECT * FROM MOVIES
JOIN SEANSES ON MOVIES.Id = MOVIES.Id
WHERE EXISTS (SELECT * FROM SEANSES WHERE SEANSES.Id = SEANSES.Id)

--TASK3
SELECT SEANSES.Time,SEANSES.MovieLanguageId,SEANSES.SubtitleLanguageId,SEANSES.Price, HALLS.Name AS 'HallName', BRANCHES.Name AS 'BrancName' FROM SEANSES
JOIN HALLS ON HALLS.Id = HALLS.Id
JOIN BRANCHES ON BRANCHES.Id = BRANCHES.Id

--TASK4 HALLDA ANCAQ AD OLDUGU UCUN ANCAQ ADI SELECT ELEDIM
SELECT H.Name, (SELECT COUNT(HallId) FROM Seanses WHERE HallId = H.Id) AS 'SEANS SAYI' FROM HALLS AS H

--TASK5 
INSERT INTO SEANSES
VALUES
(11,3,3,'2020/11/10',2),
(15,3,3,'2020/11/10',2)

CREATE VIEW SEASNSSAYI
AS
SELECT HALLS.Name, 
(SELECT COUNT(HallId) FROM Seanses WHERE HallId = HALLS.Id ) 
AS 
'Count' FROM HALLS


SELECT COUNT('Count') AS 'HallCount' FROM SEASNSSAYI WHERE Count > 3





